# Install script for directory: /home/niom/PROJECT/moos-ivp/ivp/src

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "1")
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

# Set path to fallback-tool for dependency-resolution.
if(NOT DEFINED CMAKE_OBJDUMP)
  set(CMAKE_OBJDUMP "/usr/bin/objdump")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/usr/local/bin/")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/usr/local/bin" TYPE DIRECTORY PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE FILES "/home/niom/PROJECT/moos-ivp/bin/")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/usr/local/lib/")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/usr/local/lib" TYPE DIRECTORY FILES "/home/niom/PROJECT/moos-ivp/lib/")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/usr/local/include/")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/usr/local/include" TYPE DIRECTORY FILES "/home/niom/PROJECT/moos-ivp/include/" FILES_MATCHING REGEX ".*\\.h")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/home/niom/PROJECT/moos-ivp/ivp/src/lib_behaviors/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/lib_bhvutil/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/lib_behaviors-marine/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/lib_genutil/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/lib_geometry/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/lib_behaviors-colregs/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/lib_polar/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/lib_helmivp/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/lib_ivpbuild/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/lib_ivpsolve/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/lib_logic/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/lib_ivpcore/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/lib_evalutil/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/lib_encounters/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/lib_apputil/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/lib_contacts/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/lib_obstacles/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/lib_realm/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/lib_ufield/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/lib_logutils/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/lib_mbutil/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/lib_manifest/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/lib_marine_pid/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/lib_turngeo/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/lib_dep_behaviors/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/lib_behaviors-visflocking/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/lib_behaviors-boundary/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/lib_ipfview/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/lib_marineview/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/lib_zaicview/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/lib_ucommand/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_alogpick/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_nzero/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_projpt/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_alogbin/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_alogavg/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_alogtm/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_alogeval/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_alogload/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_aloggrep/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_alogscan/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_alogcd/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_alogpare/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_alogeplot/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_alogrm/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_alogiter/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_alogcat/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_alogclip/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_aloghelm/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_nsplug/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_pickpos/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_manifest_test/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_tagrep/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_gen_moos_app/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_alogmhash/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/pRealm/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/pEchoVar/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/pHelmIvP/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/pDeadManPost/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/pNodeReporter/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/pObstacleMgr/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/uFldNodeBroker/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/uHelmScope/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/uFldMessageHandler/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/uTimerScript/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/uProcessWatch/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/uMemWatch/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/uLoadWatch/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/uTermCommand/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/uXMS/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/uMAC/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/uPokeDB/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/uQueryDB/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/pHostInfo/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/iSay/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/pContactMgrV20/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/pMarinePIDV22/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/uSimMarineV22/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/uSimMarineV23/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/pMissionHash/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/pMissionEval/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/iBlinkStick/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/pSimVisionServer/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/uFlockEvaluator/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_alogsplit/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_alogsort/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_alogcheck/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_alogtest/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_gen_obstacles/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_bhv2graphviz/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/pXRelay/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/uFldCollObDetect/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/uFldCollisionDetect/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/uFldPathCheck/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/uFldShoreBroker/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/uFldObstacleSim/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/uFldScope/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/uFldNodeComms/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/uFldBeaconRangeSensor/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/pSearchGrid/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/uFldGenericSensor/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/uFldContactRangeSensor/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/uFldDelve/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_bweb/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_mhash_gen/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_projfield/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/pMapMarkers/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_ffview/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_geoview/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_alogview/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_zaic_hleq/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_zaic_vect/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_zaic_hdg/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_zaic_spd/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/app_zaic_peak/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/pMarineViewer/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/uFunctionVis/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/uMACView/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/uPlotViewer/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/uCommand/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/dep_pBasicContactMgr/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/dep_uSimMarine/cmake_install.cmake")
  include("/home/niom/PROJECT/moos-ivp/ivp/src/dep_pMarinePID/cmake_install.cmake")

endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
if(CMAKE_INSTALL_LOCAL_ONLY)
  file(WRITE "/home/niom/PROJECT/moos-ivp/ivp/src/install_local_manifest.txt"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
endif()
if(CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_COMPONENT MATCHES "^[a-zA-Z0-9_.+-]+$")
    set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
  else()
    string(MD5 CMAKE_INST_COMP_HASH "${CMAKE_INSTALL_COMPONENT}")
    set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INST_COMP_HASH}.txt")
    unset(CMAKE_INST_COMP_HASH)
  endif()
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  file(WRITE "/home/niom/PROJECT/moos-ivp/ivp/src/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
endif()
